// <auto-generated />
using System;
using DataAccess.Concrete.EntityFramework.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Entities.Concrete.Admin", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Position")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("UserId");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("Entities.Concrete.Advert", b =>
                {
                    b.Property<int>("AdvertId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdvertId"), 1L, 1);

                    b.Property<int>("AdvertCategoryCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("AdvertName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AdvertSummary")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeleteUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quota")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdateUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("WorkplaceId")
                        .HasColumnType("int");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.HasKey("AdvertId");

                    b.HasIndex("AdvertCategoryCategoryId");

                    b.HasIndex("WorkplaceId");

                    b.ToTable("Adverts");
                });

            modelBuilder.Entity("Entities.Concrete.AdvertCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"), 1L, 1);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Categorydefinition")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("CategoryId");

                    b.ToTable("AdvertCategories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Software",
                            Categorydefinition = "Companies that provide services in the field of software."
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Architecture",
                            Categorydefinition = "Companies serving in the field of architecture.."
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Automobile",
                            Categorydefinition = "Companies serving in the field of automobile."
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Machine",
                            Categorydefinition = "Companies serving in the field of machine."
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Build",
                            Categorydefinition = "Companies serving in the field of build."
                        });
                });

            modelBuilder.Entity("Entities.Concrete.AdvertDetail", b =>
                {
                    b.Property<int>("AdvertId")
                        .HasColumnType("int");

                    b.Property<string>("CompanyInfo")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Facilities")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Quality")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Wage")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("WorkDefinition")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("WorkEnvironment")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("WorkHour")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("AdvertId");

                    b.ToTable("AdvertDetails");
                });

            modelBuilder.Entity("Entities.Concrete.Appeal", b =>
                {
                    b.Property<int>("AppealId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppealId"), 1L, 1);

                    b.Property<int>("AdvertId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeleteUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EvaluationState")
                        .HasColumnType("bit");

                    b.Property<int>("InternId")
                        .HasColumnType("int");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.HasKey("AppealId");

                    b.HasIndex("AdvertId");

                    b.ToTable("Appeals");
                });

            modelBuilder.Entity("Entities.Concrete.AppealEvaluation", b =>
                {
                    b.Property<int>("AppealId")
                        .HasColumnType("int");

                    b.Property<string>("Conclusion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ConclusionDetail")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("InternApproval")
                        .HasColumnType("bit");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.HasKey("AppealId");

                    b.ToTable("AppealEvaluations");
                });

            modelBuilder.Entity("Entities.Concrete.Education", b =>
                {
                    b.Property<int>("EducationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EducationId"), 1L, 1);

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeleteUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("EducationLevelEnum")
                        .HasColumnType("int");

                    b.Property<int>("EducationStateEnum")
                        .HasColumnType("int");

                    b.Property<string>("EndYear")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<Guid>("InternId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SchoolName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("StartYear")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.HasKey("EducationId");

                    b.HasIndex("InternId");

                    b.ToTable("Educations");
                });

            modelBuilder.Entity("Entities.Concrete.Intern", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Adress")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("WorkplaceInternId")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("WorkplaceInternId");

                    b.ToTable("Interns");
                });

            modelBuilder.Entity("Entities.Concrete.Talent", b =>
                {
                    b.Property<int>("TalentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TalentId"), 1L, 1);

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeleteUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InternId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TalentExplanation")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<int>("TalentLevelEnum")
                        .HasColumnType("int");

                    b.Property<string>("TalentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.HasKey("TalentId");

                    b.HasIndex("InternId");

                    b.ToTable("Talents");
                });

            modelBuilder.Entity("Entities.Concrete.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeleteUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Number")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Entities.Concrete.WorkHistory", b =>
                {
                    b.Property<int>("WorkHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkHistoryId"), 1L, 1);

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeleteUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InternId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OperationTime")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("WorkStateEnum")
                        .HasColumnType("int");

                    b.Property<string>("WorkplaceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.HasKey("WorkHistoryId");

                    b.HasIndex("InternId");

                    b.ToTable("WorkHistories");
                });

            modelBuilder.Entity("Entities.Concrete.Workplace", b =>
                {
                    b.Property<int>("WorkplaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkplaceId"), 1L, 1);

                    b.Property<Guid>("AdminId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeleteUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("EmployeesCount")
                        .HasColumnType("int");

                    b.Property<string>("Mission")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<string>("Vision")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<string>("WorkplaceExplanation")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("WorkplaceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.HasKey("WorkplaceId");

                    b.HasIndex("AdminId");

                    b.ToTable("Workplaces");
                });

            modelBuilder.Entity("Entities.Concrete.WorkplaceIntern", b =>
                {
                    b.Property<int>("WorkplaceInternId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkplaceInternId"), 1L, 1);

                    b.Property<DateTime>("AcceptDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeleteUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("InternId")
                        .HasColumnType("int");

                    b.Property<int>("WorkplaceId")
                        .HasColumnType("int");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.HasKey("WorkplaceInternId");

                    b.HasIndex("WorkplaceId");

                    b.ToTable("WorkplaceInterns");
                });

            modelBuilder.Entity("Entities.Concrete.Admin", b =>
                {
                    b.HasOne("Entities.Concrete.User", "User")
                        .WithOne("Admin")
                        .HasForeignKey("Entities.Concrete.Admin", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entities.Concrete.Advert", b =>
                {
                    b.HasOne("Entities.Concrete.AdvertCategory", "AdvertCategory")
                        .WithMany("Adverts")
                        .HasForeignKey("AdvertCategoryCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Concrete.Workplace", "Workplace")
                        .WithMany("Adverts")
                        .HasForeignKey("WorkplaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdvertCategory");

                    b.Navigation("Workplace");
                });

            modelBuilder.Entity("Entities.Concrete.AdvertDetail", b =>
                {
                    b.HasOne("Entities.Concrete.Advert", "Advert")
                        .WithOne("AdvertDetail")
                        .HasForeignKey("Entities.Concrete.AdvertDetail", "AdvertId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Advert");
                });

            modelBuilder.Entity("Entities.Concrete.Appeal", b =>
                {
                    b.HasOne("Entities.Concrete.Advert", "Advert")
                        .WithMany("Appeals")
                        .HasForeignKey("AdvertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Advert");
                });

            modelBuilder.Entity("Entities.Concrete.AppealEvaluation", b =>
                {
                    b.HasOne("Entities.Concrete.Appeal", "Appeal")
                        .WithOne("AppealEvaluation")
                        .HasForeignKey("Entities.Concrete.AppealEvaluation", "AppealId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Appeal");
                });

            modelBuilder.Entity("Entities.Concrete.Education", b =>
                {
                    b.HasOne("Entities.Concrete.Intern", "Intern")
                        .WithMany("Education")
                        .HasForeignKey("InternId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Intern");
                });

            modelBuilder.Entity("Entities.Concrete.Intern", b =>
                {
                    b.HasOne("Entities.Concrete.User", "User")
                        .WithOne("Intern")
                        .HasForeignKey("Entities.Concrete.Intern", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Entities.Concrete.WorkplaceIntern", "WorkplaceIntern")
                        .WithMany("Interns")
                        .HasForeignKey("WorkplaceInternId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("WorkplaceIntern");
                });

            modelBuilder.Entity("Entities.Concrete.Talent", b =>
                {
                    b.HasOne("Entities.Concrete.Intern", "Intern")
                        .WithMany("Talent")
                        .HasForeignKey("InternId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Intern");
                });

            modelBuilder.Entity("Entities.Concrete.WorkHistory", b =>
                {
                    b.HasOne("Entities.Concrete.Intern", "Intern")
                        .WithMany("WorkHistory")
                        .HasForeignKey("InternId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Intern");
                });

            modelBuilder.Entity("Entities.Concrete.Workplace", b =>
                {
                    b.HasOne("Entities.Concrete.Admin", "Admin")
                        .WithMany("Workplace")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("Entities.Concrete.WorkplaceIntern", b =>
                {
                    b.HasOne("Entities.Concrete.Workplace", "Workplace")
                        .WithMany("WorkplaceInterns")
                        .HasForeignKey("WorkplaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workplace");
                });

            modelBuilder.Entity("Entities.Concrete.Admin", b =>
                {
                    b.Navigation("Workplace");
                });

            modelBuilder.Entity("Entities.Concrete.Advert", b =>
                {
                    b.Navigation("AdvertDetail")
                        .IsRequired();

                    b.Navigation("Appeals");
                });

            modelBuilder.Entity("Entities.Concrete.AdvertCategory", b =>
                {
                    b.Navigation("Adverts");
                });

            modelBuilder.Entity("Entities.Concrete.Appeal", b =>
                {
                    b.Navigation("AppealEvaluation")
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.Concrete.Intern", b =>
                {
                    b.Navigation("Education");

                    b.Navigation("Talent");

                    b.Navigation("WorkHistory");
                });

            modelBuilder.Entity("Entities.Concrete.User", b =>
                {
                    b.Navigation("Admin")
                        .IsRequired();

                    b.Navigation("Intern")
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.Concrete.Workplace", b =>
                {
                    b.Navigation("Adverts");

                    b.Navigation("WorkplaceInterns");
                });

            modelBuilder.Entity("Entities.Concrete.WorkplaceIntern", b =>
                {
                    b.Navigation("Interns");
                });
#pragma warning restore 612, 618
        }
    }
}
